const senhaCorreta = "Leovegildo1234@"; // Você escolhe a senha

if (!localStorage.getItem('logado')) {
    const senha = prompt("🔐 Digite a senha para acessar o sistema:");
    if (senha === senhaCorreta) {
        localStorage.setItem('logado', 'true');
    } else {
        alert("Senha incorreta!");
        document.body.innerHTML = "<h1 style='text-align:center; margin-top:50px;'>Acesso negado!</h1>";
        throw new Error("Acesso negado");
    }
}

const alunosIniciais = {
    "1ºA EPT": [
        "THALITA JULIS DE ALMEIDA ARAUJO",
        "ANNA JÚLLIA DOS SANTOS RAMOS",
        "BRENO JUAN MIRANDA BIANCHI DOS SANTOS",
        "ANA VITORIA LIMA DA SILVA",
        "BEATRIZ ORTOLAN DE OLIVEIRA",
        "CALEBE OLIVEIRA DA SILVA",
        "EMANUELLE VICTÓRIA LUCIANO BRITO",
        "EVERTON FELIPE ALMEIDA COSTA",
        "GABRIELLY VITORIA PRADO PEDAIS",
        "KALEBE ALVES RIBEIRO",
        "LAURYANE ALMEIDA RISSATO",
        "LUIZ FELIPE BRILHANTE FRANÇA",
        "LUIZ GUILHERME ARCANGELO DE ALMEIDA",
        "MARIA CLARA MARCONDES RODRIGUES",
        "MARIA EDUARDA CORREA SILVA",
        "MATHEUS GUILHERME SANTOS DE ARRUDA",
        "MYLLENA MARQUES NEVES",
        "NICOLAS KAUÃ PESSOA DE OLIVEIRA",
        "RENAN MORAIS DA MOTA",
        "RYAN PEREIRA DE AZEVEDO",
        "THALYTA SARA QUEIROZ DOS SANTOS",
        "VALÉRIA MARIM RODRIGUES DA SILVA",
        "VIVIANNY KRISTHINE SOUZA SIQUEIRA",
        "AMANDA VITORIA FRANCO MORAES",
        "MANOELA LUCIA DA SILVA CAMPOS",
        "PEDRO JORGE DA SILVA MOURA",
        "NATHALY VITORIA MOREIRA DE OLIVEIRA",
        "MARIA FERNANDA TOLEDO MARCONDES",
        "VITORIA OLIMPIA DA CRUZ",
        "TALITA DA SILVA SOARES",
        "ÁQUILA SOARES DE ARAÚJO GUSMÃO",
        "ANNA JULIA ROSA SANTOS DE SIQUEIRA",
        "ALICE YARA DA SILVA LEITE",
        "DANIEL FERNANDO RODRIGUES GOMES"
    ],
    "1ºB EPT": [
        "ALINE FERNANDA CAVALCANTI SIQUEIRA",
        "FRANCISCO MEDEIROS PEREIRA DE SOUZA",
        "HIARLY MENDES SILVERIO",
        "JOÃO GABRIEL SILVA DE OLIVEIRA SANTOS",
        "NABILLY SABRINNY CONSTANTINO PEREIRA PIANTKOSKI",
        "EVELYN CONCEIÇÃO SANTOS",
        "PEDRO HENRIQUE GOMES RODRIGUES",
        "VITORIA EDUARDA BERTOLDO DA SILVA",
        "ISADORA APARECIDA RODRIGUES DA SILVA",
        "WESLEY MATHEUS RODRIGUES BICHARRA",
        "TYAGO DA SILVA ROCHA CAIS",
        "DAVI GUILHERME FERREIRA DOS SANTOS",
        "GEOVANNA MARIANA DE ARAÚJO ROCHA",
        "ANA RITA DE LIMA BRITO",
        "ANNA LÚCYA DA SILVA XAVIER",
        "ISABELLA VELOZO BRITO DE MORAES",
        "PEDRO HENRIQUE ROBERTO ALVES",
        "RAFAELA RIBEIRO BORGES",
        "LUAN DAVI FREITAS SODRE",
        "PEDRO HENRIQUE SILVA ALVES MIRANDA SOARES",
        "ISABELLY LUCIANE LIMA DOS REIS",
        "LUIS ARTHUR DE OLIVEIRA MORAES",
        "KENNYDY CAMPOS GOMES",
        "PAULO GABRIEL DOS SANTOS SAMPAIO",
        "RAUA REZENDE DE LIMA FRANÇA",
        "AGATHA VICTORIA OLIVEIRA DE AMORIM",
        "LUIGY VINICIUS DA SILVA BARBOSA",
        "ANA GABRIELLA TAVARES DA SILVA",
        "HENRRY RIBEIRO COTRIM",
        "ANA LUIZA MENDES OLIVEIRA",
        "SAMUEL AUGUSTO DA SILVA",
        "ISABELA CERQUEIRA ROMAO DA SILVA",
        "KAUÃ MANOEL FIRMINO ROCHA",
        "AKHYLLES KAUAN NASCIMENTO MACHADO",
        "ENZO GAUDENCIO DO AMARAL ARAUJO",
        "JOÃO VITOR MIRANDA DE OLIVEIRA",
        "ISABELLA AMORIM DE SOUZA",
        "RICARDO SILVA MOREIRA"
    ],
    "1ºC": [
        "MARIANA DOS SANTOS IBANEZ",
        "LUIZ FABIANO ALMEIDA DIAS DA SILVA",
        "LUIZ FELIPE DE SOUZA FERREIRA",
        "MANDYLANY AMORIM DA SILVA",
        "NASLAINY JULIA CARVALHO MAGALHAES",
        "NAYRA PEREIRA DE SOUZA",
        "NICOLLAS GABRIEL GOMES DE ARAUJO",
        "RAFAELA VITÓRIA SANTOS SOUZA",
        "SAMUEL MATIAS CORREA",
        "WAGNER SOARES DE SOUSA",
        "AGHATA PAOLA ARAÚJO FIGUEIREDO",
        "ANNA LUYZA BRAGA DE ALMEIDA",
        "BEATRIZ VITORIA FERREIRA DE ALMEIDA",
        "CRISTIAN FERREIRA DE LIMA",
        "DAFINY GABRIELE SILVA FARIAS",
        "DANIEL ALBUQUERQUE DA SILVA",
        "DIEGO SOUZA DO NASCIMENTO",
        "EDIMILSON CRUZ DE ANDRADE",
        "EMERSON SILVA ARAUJO",
        "ISAAC VINICIUS NASCIMENTO COSTA",
        "JESUS ALEJANDRO MAITA TAMICHE",
        "LAVINIA SOFIA FARIA FRANÇA",
        "LEONA LYNKON MARTINS PEDROSA",
        "LUAN RICARDO OLIVEIRA FERNANDES",
        "LUCAS GABRIEL BRIVES DE SOUSA",
        "ANA CRISTINA CAETANO HONORATO",
        "WELLYSON CAMPOS DOS SANTOS",
        "PEDRO HENRIQUE DA SILVA DOMINGOS",
        "GUSTAVO JESUS DOS SANTOS PEIXOTO",
        "WESLLEN JHORDAN CARVALHO",
        "LAIS BIANCA MARTINS AMADOR",
        "CRISTHYANNO RONALDO LIMA SIQUEIRA",
        "ANA BEATRIZ PEREIRA PAES",
        "GABRIELE VITÓRIA DIAS DE SOUZA",
        "RYCHARD WILSON SEGOVIA OLIVEIRA",
        "SCARLY GABRIELA MOREY PALMA",
        "BRENNO RANGEL SANTOS SILVA GONÇALVES",
        "GABRYELE AMANDA TEIXEIRA DA SILVA",
        "BRUNO MATEUS OLIVEIRA ARAUJO"
    ],
    "1ºD": [
        "ANA MARIA DE ALMEIDA SILVA",
        "DAVID GABRIEL RODRIGUES DE ABREU",
        "EMILLY KAUANE MAZETTO DA SILVA",
        "EMILLY RUTH DA SILVA SANTOS",
        "FLAVIO GONÇALVES DE PAULA JUNIOR",
        "GABRIEL HENRIQUE AGUIAR DA SILVA",
        "HIGOR ALMEIDA SOUZA",
        "ISABELLI KAUANI GUIMARAES LEMES",
        "JOCIMEIRE ASSIS DA COSTA",
        "MARIA EDUARDA DE FIGUEIREDO AMORIM",
        "MARIA EDUARDA DOS SANTOS SILVA",
        "MARIA EDUARDA MACHADO MARQUES",
        "REBECA MATIAS DE ANDRADE MELO",
        "RENATO RODRIGUES BATISTA DE AMORIM",
        "VITOR GABRIEL CERCINDO DE CARVALHO",
        "KELVEN KAUAN SILVA DE SOUZA",
        "LAIANY PEROLA BEATRIZ ORMOND",
        "LAUANNY GABRIELY PEREIRA VIANA STECANELLA",
        "LETICIA ESTÉPHANY POQUIVIQUI BONJARDIM",
        "LUCAS DANIEL PEREIRA DE ALMEIDA",
        "LUCAS NUNES AMORIM",
        "LUIS FERNANDO DE SOUZA SILVA",
        "LUIZ ROGERIO SANTOS OLIVEIRA",
        "WANDERSON GABRIEL ALVES LOPES",
        "YSIS DAFFINY RAMOS FAGUNDES",
        "ARIEL ANTONIO BISPO DO ESPIRITO SANTO",
        "ELOISA FERNANDA FERREIRA PONTES",
        "RAFAEL KAUAN SANTOS ALMEIDA",
        "GUILHERME PEIXOTO GOMES",
        "KAUAN FELIPE PEREIRA DA SILVA",
        "ISABELLY VITORIA MORAES DE ALMEIDA",
        "ANA LUÍZA ALBUQUERQUE BONFIM",
        "JOÃO PEDRO DE SIQUEIRA MARTINS"
    ],
    "1ºE": [
        "THALITA KAUANY DIAS DE SOUZA",
        "VITORIA BIANCA DO NASCIMENTO DA CRUZ",
        "YAGO EMANOEL JESUS MORENO",
        "EMERSON JUNIOR LIMA DA CRUZ",
        "EMILLY CARREIRA MILANEZ REZENDE",
        "GABRIEL ESTEVAO SANTOS DO NASCIMENTO",
        "GABRIELLY LEONCIO DA SILVA",
        "GUILHERME GOMES MUNDEL",
        "GUILHERME LARA SILVA",
        "ISABEL CRISTINA DE SOUZA OLIVEIRA",
        "ISABELLY LORAINY DE OLIVEIRA TEIXEIRA",
        "ANA CLARA AZEVEDO DOS SANTOS",
        "ANDERSON SALOMÃO CARDOSO ARAÚJO",
        "ANDRESSA ALVES DA SILVA",
        "BRUNO FELIPE ROSSETTO DA SILVA",
        "CAUÃ GABRIEL BASTOS GONÇALVES",
        "JOANA CYNARA MONTEIRO DE ARAUJO",
        "JUNIOR PABLO EVANGELISTA DE AQUINO",
        "KIMBERLY EDUARDA EVANGELISTA DA SILVA",
        "MANUELLA CRISTINA SILVA",
        "MIGUEL AZEVEDO MORAES",
        "NAFTALY AIRA SILVA DOS SANTOS",
        "RAMON NASSARDEN COSTA",
        "LUCAS GUILHERME LEITE DA CUNHA",
        "RHUAN GUILHERMY OLIVEIRA FRANCO VAZ GUIMARAES",
        "PEDRO HENRIQUE FIGUEIREDO",
        "BRUNO LUCAS DOS SANTOS TEIXEIRA",
        "EMANUELLY ALVES TOLENTINO SILVA",
        "RAPHAEL ABRAÃO COSTA GONZAGA",
        "GEICIANI ARRUDA SILVA",
        "EDUARDA GUIMARAES",
        "GUSTAVO BORGES DE BARROS FERREIRA",
        "VERONICA MOREIRA SILVA PEDROSO",
        "LAUANNY PAULA FERREIRA NUNES",
        "ADILES VITORIA MOIA BRANDAO",
        "BRUNO GUILHERME DIAS",
        "THIAGO JOSÉ SANTOS DE ARRUDA",
        "JULIA KAROLINE PINHEIRO DA CRUZ",
        "EMILLY VIVIAN DA PENHA SILVA"
    ],
    "2ºA EPT": [
        "ALAN GABRIEL FERREIRA LOPES",
        "ANDRESSA VITORIA ARAUJO DA CRUZ",
        "BRITANY GABRIELLY GONÇALVES",
        "CARLOS EDUARDO MOREIRA DA SILVA",
        "EDEN RONAN ALEMAN NEVES",
        "EZEQUIEL EVANGELISTA MARANHÃO",
        "FABIO ANTONIO DA SILVA HENRIQUE",
        "FELIPE DOS SANTOS",
        "HENZO DE PAULA GARCIA DA SILVA",
        "IHAGO LEANDRO ANTUNES RODRIGUES PEREIRA",
        "ISABELLY CRYSTYNI ALMEIDA ROCHA",
        "ISABELLY PATRICIA COSTA ALVES",
        "JACQUESON HIEGO DOS SANTOS NUNES",
        "LUCAS BENITES ANDRADE",
        "LUIS HENRIQUE DA SILVA PEDROSO GONÇALVES",
        "MATEUS RIKELMY DE ARRUA MARTINS",
        "MIGUEL DA SILVA FREITAS AMORIM",
        "MIRANDA FRANCISCA AUDAIN CABRERA",
        "RICHARD GABRIEL DE MORAIS FIGUEIREDO ROSA",
        "SARAH RAQUELY DE MORAES RIBEIRO",
        "THÉO FILLIPE DE FIGUEIREDO AMORIM",
        "THYELLEN OHANNA MIRANDA DE CAMPOS",
        "WGLEDSON DOS SANTOS BORGES",
        "YURI GABRIEL DE OLIVEIRA ASSUNÇÃO",
        "FABRICIO WILLY DA SILVA SANTOS DE MELO",
        "GIOVANNA VITORIA OLIVEIRA SANTANA",
        "AMANDA CAROLINE DA SILVA VAZ"
    ],
    "2ºB EPT": [
        "ANTÔNIO GUSTAVO FERREIRA CAJAHIBA",
        "ALLAN ESEQUIEL AMORIM DA SILVA SANTOS",
        "AMANDA DE ALMEIDA ALVES",
        "ARYADNE KAMILLY LIMA DA SILVA",
        "CARLOS HENRIQUE OLIVEIRA MORAES DE SOUZA",
        "CLARA BEATRIZ FIGUEIREDO GAMA",
        "DAVID LUCAS GOMES PEREIRA",
        "ERICK DAVI ROSA DA SILVA",
        "GRACIELY MARQUES DA SILVA ASSUNÇÃO",
        "HEMILLY FERNANDA DA COSTA SILVA",
        "ISABEL KAROLLYNE CARVALHO SILVA",
        "ISABELLY SOUZA CAMPOS",
        "ISADORA RAFAELLY MONTEIRO CUNHA",
        "JEAN LUCAS SILVA VENTURA",
        "JEOVANA VITORIA MARTINS ALVES",
        "JULIA BEATRIZ MELO LIMA DA SILVA",
        "KAUA VITOR DA CRUZ ARRUDA",
        "LUIZ JONNY COSTA MASSALAI",
        "LUKAS GABRIEL DA CRUZ CARDOSO",
        "MARIA EDUARDA CARDOSO ARAÚJO",
        "MATHEUS SILVA DO ROSÁRIO",
        "MIGUEL AUGUSTO BENITES ARCANJO",
        "MURILO DE SOUZA ANDRADE",
        "PIETRA DIAS FERREIRA GOMES",
        "RAELY MORAES ALMEIDA FERRAZ",
        "RENATA CONCEIÇÃO DE QUEIROZ",
        "THALYTA VITÓRIA FONTES PEREIRA",
        "VICTOR AGUERO DE SOUZA",
        "YASMIM SOFHIA SILVA",
        "CHRISTIAN SENA SOARES DA SILVA SANTOS",
        "LUIS HENRIQUE DE OLIVEIRA RAMOS",
        "ISABELLY VITORIA MORAES DE ALMEIDA",
        "GABRIELE VITÓRIA DIAS DE SOUZA",
        "LUIS GUSTAVO FERREIRA DA SILVA",
        "RAFAELY DOREA AQUINO DA SILVA",
        "SOFIA LOURENÇO AMORIM DE QUEIROZ"
    ],
    "2ºC": [
        "GUSTAVO HENRIQUE CONCEIÇÃO XAVIER",
        "ANA ALICE DE FRANÇA SANTOS",
        "ANNYELLY VITORIA SANTOS RAMOS",
        "AQUILES FRANÇA DO NASCIMENTO",
        "CARLOS DANIEL RENGEL MEDINA",
        "CLAUDIELLE NATHALIA GOMES ROCHA",
        "DANIEL LUKAS SILVA SOARES",
        "DAVI DA SILVA FERREIRA",
        "HYASMIN VITORIA PRADO PEDAIS",
        "ISABELLA CRISTINY VIEIRA OLIVEIRA",
        "JOAO PAULO ROCHA DAUFENBACH",
        "JONAS GABRIEL FERNANDES SIQUEIRA",
        "KAREN ISABELA DE OLIVEIRA LIMA",
        "KETLYN IZABELY SANTOS DE LIMA",
        "MAYCON RUAN SALAZAR MARINHO",
        "MIGUEL RUAN SALAZAR MARINHO",
        "MISLAINY MIRANDA MAGALHAES COSTA",
        "NICOLY MAYSA SALVATERRA FERNANDES",
        "RAFAELLI VITORIA NUNES DE CARVALHO",
        "RENAN MENDES DA SILVA",
        "RHUAN MICHEL ANTONIO DA SILVA SOUZA",
        "RHYAN PINHEIRO DE CAMPOS",
        "THAYARA QUIMBERLYN RAMOS DA SILVA",
        "TIELLY LOUISE CEBALHO DA SILVA",
        "DANILO SANTOS CARDOSO",
        "JONATHAN GABRIEL CAMPOS AMORIM",
        "ANA KARLA OLIVEIRA DE SOUZA",
        "VITORIA KAMYLA COSTA LEIRIAS",
        "SOFIA ELOISA AMORIM BRITO",
        "ANA JULLIA DE SOUZA BRITO",
        "DEBORA CRISTINA PRADO CORREIA",
        "LUCAS LUAN LOUZADA DE RAMOS",
        "ISABELLA RENATA ALVES DA SILVA",
        "RAYSSA LEILIANE CRUZ DE ALMEIDA GUIA"
    ],
    "2ºD": [
        "KAYRON ALEXANDRE SABOIA RODRIGUES",
        "ANTONIO MARCOS RODRIGUES DA SILVA",
        "DANIELLY ARCANJO MARTINS",
        "DAVID NETO ABDALLAH DE FARIA",
        "DEBORA VITORIA MORAES BISPO",
        "ERIC GABRIEL EGUEZ TALON",
        "GABRIEL OLIVEIRA PEREIRA",
        "HESHELEN REGINA SENABIO SCHREINER",
        "JOÃO EMANOEL GARCIA ALVES",
        "JOÃO LUCAS FELIX DA SILVA",
        "JOÃO PEDRO MENDES DE SOUZA",
        "LUCAS VINICIUS AGUIAR AMORIM DE SOUZA",
        "LUIS APARECIDO COUTINHO DE ALMEIDA",
        "LUIS FERNANDO ANDRADE VENANCIO",
        "MARCOS PAULO ALMEIDA DA SILVA MORAES",
        "MATEUS LIMA DA SILVA",
        "MATHEUS ALVES DA SILVA",
        "RONALD SEBASTIÃO JUNIOR MIRANDA ALVES",
        "SAMUEL JACSONY SIQUEIRA DE MATOS",
        "SARA ALCANGELA DE OLIVEIRA",
        "THAVIANE VITORIA PEREIRA DE ALMEIDA",
        "THAYLLA RAYANNY ARCANJELA FERNANDES ARAGÃO",
        "YARA GABRIELA SANTOS",
        "YASMIM PEREIRA BASTOS",
        "THABATA CRISTYNNI ALMEIDA DE ARRUDA",
        "THOBIAS MIGUEL MORAES LOPES",
        "HEITOR SILVA RODRIGUES",
        "GABRIEL MEDEIROS DE LIMA"
    ],
    "2ºE": [
        "ISABELLY CAROLINE PACHECO COELHO",
        "RARYANE VITORIA DE SOUZA BRITO SANTANA",
        "MAYCON FELIPE PEREIRA DA SILVA",
        "RIAN SILVA MOREIRA",
        "ANDRESSA CHAVES DOS SANTOS",
        "ANNA KAROLYNA BEZERRA JESUS ALENCAR",
        "DAVID CRISTIANO SOUZA RODRIGUES",
        "EDUARDA LAYZE PIRES DE OLIVEIRA",
        "EMILY RHIANY SANTANA GOMES",
        "ESTEPHANI BIANCA DOS SANTOS DA CRUZ",
        "FELIPE URTADO FERREIRA",
        "GABRIEL VINICIUS DE DEUS PAULA",
        "GILLIAN MESSIAS SCHAFER",
        "IGOR GABRIEL CUNHA DE ARRUDA",
        "IZADORA LUIZA SILVA REZENDE",
        "KASSIANY VITÓRIA DE CAMPOS COENGA",
        "KEMILLY VITORIA DE ASSIS RODRIGUES",
        "LUCAS EDUARDO DORNELAS ROCHA DE ARAUJO",
        "LUCAS GABRIEL DE JESUS AZAMBUJA",
        "MARIA EDUARDA GOMES",
        "MILLENY SOPHIA SANTANA TRISTAO",
        "PEDRO HENRIQUE DE ANDRADE SOUSA",
        "CRISTYAN GABRIEL VIANA GARCIA",
        "ESTÉFANI OLIMPIA DA CRUZ",
        "LEONARDO GAMA DOS SANTOS",
        "WILLIAN MICHEL DOS SANTOS ALMEIDA",
        "MARIANY DIAS ALVES DE SOUZA",
        "LAYNA MAELLY GONCALVES DE OLIVEIRA",
        "DANILO FERREIRA OLIVEIRA",
        "LINDALVA KAMILLE FARIAS AZEVEDO",
        "MARCO ANTÔNIO GOMES SOARES",
        "EMILLY VIVIAN DA PENHA SILVA"
    ],
    "3ºA EPT": [
        "NAUNAY CHAGAS DE AZEVEDO",
        "MARIA ELAINE MORAES BISPO",
        "MICHAELLE ARAUJO BARBOSA DE ASSIS",
        "MOISÉS RICARDO PEREIRA MENDES DA SILVA",
        "PEDRO HENRIQUE MONTEIRO SIQUEIRA COSTA",
        "RIHURY PEREIRA MONTEIRO",
        "THAYLA GABRIELLE GONÇALVES ARCANJO",
        "ADRYAN FELIPE AMORIM SAMPAIO",
        "ANDERSON ALFREDO DA SILVA ARRUDA JUNIOR",
        "CAIO REIS DE LIMA",
        "DANIEL DE ARRUDA RODRIGUES",
        "EDUARDA CRISTINA OLIVEIRA DE MORAES",
        "EMILLY VICTORIA GORGETE VILAS BOAS",
        "FELIPE MARQUES DA SILVA",
        "GABRIEL VINICIUS DOS REIS E SOUZA",
        "GABRIELLY CHRISTYNE COSTA ALVES",
        "GABRIELLY WALKIRIA DOS REIS E SOUZA",
        "GICELMY DA SILVA ASSUNÇÃO",
        "KAIO JULIANO CLARO DA SILVA",
        "LUCAS FRANCISCO SANTOS",
        "LUCAS MATEUS DE ARRUDA FIGUEIREDO",
        "LUCAS RODRIGUES DOS SANTOS",
        "RAIANNY PEREIRA MARTINS",
        "NAUANY CHAGAS DE AZEVEDO"
    ],
    "3ºB": [
        "BRUNO APARECIDO DE SOUZA GERALDES",
        "ANA VITORIA MORAES DE SOUZA",
        "JOÃO GUILHERME DA SILVA MOTA",
        "ANA LIDIA CASTILHO CANDIDO",
        "MIRELA EDUARDA RODRIGUES CARVALHO",
        "ANA CLARA RODRIGUES DE CARVALHO",
        "DANIELLE LOPES DE OLIVEIRA",
        "MARCIO DANIEL CARVALHO DE OLIVEIRA",
        "MARIANA MARTINS DE ALMEIDA",
        "MYKAELLY EDUARDA SANTOS ALMEIDA",
        "JOÃO GABRIEL BUENO DA CRUZ",
        "FELIPE GUSTAVO BARROS DE OLIVEIRA ARAÚJO",
        "JOAO LUCAS ALVES BORGES",
        "DALILA EDUARDA ARDARIOS SILVA",
        "GABRIELLY VITÓRIA DE FREITAS SOARES",
        "LUCAS FELIPE PENHA DOS SANTOS",
        "MARIA EDUARDA BRUGNARI MARTINS COSTA",
        "ISABELA CIPRIANO MERCES",
        "GEOVANNA CRISTINA CAMPOS DE OLIVEIRA",
        "YSABELLI HADASSA MACEDO DE BRITO",
        "RYAN CARLOS PEREIRA CRUZ",
        "LILIANE SAMPAIO DINIZ DE MATOS",
        "PABLO NASCIMENTO DIAS MARTINS",
        "EVILLY ADRIELE LOURENÇO DA COSTA",
        "THAMIRIS FERNANDA SANTOS SANTIAGO"
    ],
    "3ºC": [
        "JOÃO PEDRO TORRES LIMA",
        "DAVIELA VALERIA BERMUDEZ NATERA",
        "DERICK SAMUEL CABORA",
        "EMANUELLY CARVALHO DE MIRANDA",
        "FABRICIO DA SILVA DIAS JUNIOR",
        "GUILHERMY SANTANA DE OLIVEIRA",
        "HENRIQUE CARLOS DA SILVA SOUZA",
        "JEFFE DANIEL DA SILVA AMORIM PASSOS",
        "JHULLY ELOIZY GAMA DE CARVALHO",
        "JULIA VITÓRIA SAMPAIO SILVA BATISTA",
        "ADRIAN GUTIERREZ BIAZI BELEM",
        "ANA CAROLINA MELO DE ARRUDA",
        "ANA CLARA RIBEIRO REIS DA SILVA",
        "ANA JULIA DE SOUZA SILVA",
        "ANNY GRAZIELLY CUNHA XAVIER",
        "ANTONY XAVIER DA SILVA",
        "ARTHUR HENRIQUE VILA PROFESSOR",
        "BRENDA DA SILVA SAMPAIO",
        "CARLOS EDUARDO BEZERRA DA SILVA",
        "CARLOS HENRIQUE COSTA DOS SANTOS",
        "MARIA DE FATIMA NAZARE RIBEIRO ARCANJO",
        "MARIA HELOISE DA SILVA SOARES",
        "MATHEUS EDUARDO ALMEIDA DE ARRUDA",
        "MILENA RAFAELA DA SILVA JUSTINO",
        "NORLENS LOUIS",
        "RANYELE CORREA DA SILVA",
        "SABRINA ALVES GOMES",
        "SAMIRA ALVES GOMES",
        "WENYKHE SOUZA DIAS",
        "MARIA VITÓRIA CARVALHO DE SOUZA",
        "GABRIEL DE SOUZA COSTA",
        "DEIVID KAUA LIMA DE ALMEIDA SANTANA",
        "THAMYRIS FERNANDA ALVES DOS SANTOS",
        "AMANDA GABRYELLE DE ALMEIDA"
    ],
    "3ºD": [
        "LILIANE SAMPAIO DINIZ DE MATOS",
        "HILDA FERNANDA CARNEIRO ROCHA",
        "STHER LUIZZE DA SILVA NASCIMENTO",
        "AMANDA CRISTINA DA COSTA E SILVA",
        "ANA VITORIA BISPO DA SILVA",
        "EZEQUIEL FERNANDES SIQUEIRA NUNES",
        "FELLIPE GABRIEL CURADO GALESKI",
        "GIOVANA GABRIELLY DOS SANTOS PAIXÃO",
        "ISABELLA DA CONCEIÇÃO PRIOSTI",
        "ISIS LUNA PEREIRA GONÇALVES",
        "JESSIKA GABRIELA DA SILVA SANTOS LINO",
        "JULIA VITORIA VARGAS DE JESUS",
        "LANDERSON PEREIRA NASCIMENTO",
        "LANDISON PEREIRA NASCIMENTO",
        "LINKON ARAUJO DE LIMA MARTINS",
        "LUCAS GABRIEL FERREIRA GOMES",
        "MARCOS HENRIQUE SANTOS CARDOZO",
        "MARIA EDUARDA PEDROSA DIAS DE SOUZA",
        "MARIA IARA NERES CARVALHO",
        "NICOLAS CAMPOS VIEIRA",
        "PEDRO DE MORAES FRANCO",
        "RAIELLY CARLA SOUSA DA SILVA",
        "SAMARA GONÇALVES SANTANA",
        "SARA BEATRIZ DE SOUZA FEITOSA",
        "THIARA FERNANDA DA SILVA RETORI",
        "WELLITA YASMIN FONTES SILVA",
        "GABRIELE VITÓRIA DIAS DE SOUZA",
        "GUSTAVO HENRIQUE VILELA SANTANA"
    ],
    "3ºE": [
        "ALERRANDRO CRISTIAN DE ALMEIDA PEREIRA",
        "DIOGO ANTONIO DA SILVA ARRUDA",
        "FELIPE MARCELO RIBEIRO PIO DA SILVA",
        "GABRIEL DE AQUINO PEREIRA",
        "GIOVANNA FRANZONI BISPO",
        "LAIANE PEREIRA DOS SANTOS",
        "LUIZ OTHAVIO PINHO BENTO",
        "MYLENA FERNANDA DO ESPIRITO SANTO AMARAL",
        "RANIELLY TAMY NOBRES BENITES",
        "ROBERT ALEXANDRE ALVES GARCIA",
        "WILLIAM SANTOS VAZ",
        "GEOVANA DA SILVA",
        "MICKAEL SANTANA SOUZA",
        "ADALBERTO VERONEZ DE MATTOS MARIANO",
        "ANTONIO HENRIQUE VERONEZ DE MATTOS MARIANO",
        "KAUÂN GUILHERME GOMES DE SIQUEIRA",
        "MAICKEL BARBOSA DE SANTANA",
        "ISADORA DA SILVA FERNANDES RODRIGUES",
        "ANA VITORIA LEOCADIO DA SILVA ALMEIDA",
        "SILVIO PIEDRO FREITAS PEREIRA",
        "RENATA VITÓRIA RODRIGUES DE ARRUDA",
        "KAUA RAFAEL RUFINO AGUIAR"
    ],
    "6ºA": [
        "ANNA JULIA ALVES DOS SANTOS",
        "GEOVANNA RAMOS BARBOSA",
        "ISAAC DE SOUZA AGUIAR",
        "KAIQUE DAVI PEREIRA SACRAMENTO",
        "VINICIUS GOMES SANTANA COELHO",
        "ELIAN DAVALO PINHEIRO",
        "MARIANNA VITORIA CAYRES DE SOUZA",
        "RAFAEL LUCAS GONÇALVES DE CAMPOS",
        "SAMUEL JUNIOR GONÇALVES DE PAULA",
        "ELIAS PAULO DE ALENCAR CLIMACO",
        "ISABELLY ARAUJO DOS SANTOS",
        "RAIMUNDO VIKTOR QUEIROZ ALVES",
        "LETICIA ISABELLY POLVERINE DE MORAIS",
        "DAVI KENNEDY LOUZADA SANTANA",
        "ANA CLARA FERREIRA DE ALMEIDA",
        "EVELLYN ANDRESSA PEREIRA NASCIMENTO",
        "ESTHER SILVA ROCHA",
        "HELOISA EDUARDA SOUZA DOS ANJOS",
        "ALESSANDRA DE JESUS SANTANA PINTO",
        "YAGO MARTINS DE ABREU",
        "JOSE ROBERTO DA SILVA MARINHO DOS SANTOS PEREIRA",
        "CARLOS ALLERANDRO OJEDA SANTOS",
        "MARIA EDUARDA MAGALHÃES RIBEIRO DE AMORIM",
        "SAMUEL NUNES DE LIMA",
        "ISABELLA ALMEIDA DA SILVA",
        "KAIK RODRIGO DOS SANTOS NETTO",
        "ALICE OLIVEIRA LEQUE",
        "SOPHIA YARA ALMEIDA SOUZA",
        "ANA CLARA SILVA MEDRADO",
        "HUGO CRISTIANO DE ALMEIDA ARAUJO",
        "GABRIEL MONCERATE DOS SANTOS"
    ],
    "6ºB": [
        "ALICE NICOLLY GOMES HAVEROTH",
        "THALITA RAFAELA CARDOSO COSTA",
        "SOPHIA ADELIA FERREIRA ROCHA BRAGA",
        "ELIZE NASCIMENTO RAMOS DO ESPIRITO SANTO",
        "JOÃO DANIEL ALVES RIBEIRO DE SENA",
        "KAMILLY CRISTINA FERREIRA LEITE DA SILVA",
        "ANA JULIA DA SILVA GONSALVES",
        "ADELE FATIMA VIEIRA DOS SANTOS",
        "ANTHONY SAMUEL LIMA DA ROCHA",
        "ANY VITORIA DA SILVA PIRES",
        "KAYRA VITORIA OLIVEIRA DE SOUZA",
        "MELISSA VITORIA MENINO MENDES DE SOUZA",
        "NICOLLY ROSENO DE AZEVEDO",
        "ARTHUR PEREIRA DE ALMEIDA",
        "ANA JULIA BARROS NASCIMENTO",
        "NATASHA AMANDA DE MORAES",
        "CAIO DAVI DA COSTA FERREIRA",
        "ANA LUIZA BEZERRA DE JESUS",
        "NICOLLY APODACA SANTANA MACHADO",
        "MARIA FERNANDA QUEIROZ OLIVEIRA DOS SANTOS",
        "GUSTAVO FAGUNDES PROFESSOR",
        "DAVI LUIZ APARECIDO FRANÇA",
        "ERICK MATHEUS DA SILVA MARTINS",
        "BERNARDO RODRIGO AMARAL",
        "SARAH VITÓRIA LOUZADA BORGES",
        "DAVI LUAN DE AMORIM LOPES",
        "BEATRIZ FERREIRA QUEIROZ",
        "LIZ ANTONIA PRUDENCIO ALVES",
        "MILLENA RODRIGUES TEIXEIRA",
        "ALANA ANTONIELY ALVES",
        "TAINA SILVA MENDES"
    ],
    "6ºC": [
        "ANNA CLARA SOARES DE OLIVEIRA",
        "ARTHUR MIGUEL BOMDEPACHO DOS SANTOS",
        "MIGUEL HENRIQUE SILVA FERREIRA",
        "NYCOLE FERNANDES FONTANELLI",
        "DAVI FERREIRA DA SILVA BRAZ",
        "PEDRO HENRIQUE VELASQUE DA SILVEIRA",
        "REBECA DE ARRUDA SANTOS",
        "NICOLE DIAS DA CONCEIÇÃO",
        "MYKAEL ARTHUR MARQUES SOARES",
        "HEITOR SANTOS ZOZOMAZORÉ",
        "VALERIA VALENTINA MEDINA MARCANO",
        "DAVI LUCCA PRADO FERREIRA",
        "MAYTTE LOYSE ALMEIDA SILVA",
        "MARIA EDUARDA FERNANDES MARTINS",
        "OSIRIS GABRIEL DE FRANÇA DALLA NORA",
        "ENZO GABRIEL OLIVEIRA ARCANJO",
        "MATHEUS HENRIQUE DOS SANTOS LIMA",
        "SARA FAUSTINO DA SILVA DE PAULA",
        "KAUAN SANTOS COELHO",
        "ALICE MARTINS VERGILIO",
        "MARIA EDUARDA RODRIGUES COSTA DA SILVA MENESE",
        "ANNA SOPHIA DA SILVA NELES",
        "RAPHAEL FERNANDO DE FRANÇA LISBOA",
        "HENZO MICHEL EVANGELISTA DE AQUINO",
        "ADRYAN MIGUEL JESUS DA SILVA",
        "AGHATA SÓFIA OLIVEIRA DE SIQUEIRA",
        "LUIZA SANTIAGO CORREA DA ROCHA",
        "MILLENA FIGUEIREDO DOS SANTOS",
        "LUIZ AUGUSTO REZENDE DE OLIVEIRA",
        "JORGE LUIZ OLIVEIRA RODRIGUES",
        "ANDERSON HENRIQUE LARA NASCIMENTO",
        "ISABELA DA SILVA SANTOS",
        "PEDRO LUCAS PEREIRA DOS SANTOS SILVA"
    ],
    "6ºD": [
        "ERIK VINÍCIUS SILVA BRUNO",
        "JOÃO EMANOEL TIBALDI MARQUES CARVALHO",
        "CARLOS EDUARDO CANDIDO SIBILIS DE BARROS",
        "MANUELLA ROMAO DE OLIVEIRA",
        "GABRIEL LORENZO DE BARROS BARBOSA",
        "MARIA LUÍSA MOREIRA DA SILVA",
        "GUSTAVO BARBOSA ARAUJO",
        "ANNA VITÓRIA BARROS MASSUD OLIVEIRA",
        "ALICIA RIBEIRO NUNES",
        "MARIA HELOISA SIQUEIRA DOS SANTOS",
        "DAVI LUCCA FERNANDES DA COSTA",
        "LAURA SOUZA DE SANTANA",
        "DANIEL MORAES DE FIGUEIREDO",
        "VALENTINA LISBOA GUSMÃO",
        "MARIA EDUARDA LIMA DA SILVA",
        "PEDRO HENRIQUE CARVALHO DE ALMEIDA",
        "ISABELA DA SILVA SANTOS",
        "EMANUELA CARDOSO DE OLIVEIRA",
        "THAYLA PRADO CARDOSO",
        "LUIZ GUSTAVO DA SILVA ARRUDA",
        "MELYSSA IZABELA ANDRADE FRANCO",
        "RAIBELYS GABRIELA ROCCA PALMA",
        "ANA FLAVIA DOS ANJOS AMORIM",
        "ARIANE NICOLY RAMOS DA SILVA SOUZA",
        "ESTER REIS MACEDO",
        "NIKOLLAS VALENTIM NAZARIO DE BURGO",
        "EMILLE ALMEIDA LAURIANO",
        "EMANUEL MEIRA BRUSCHI",
        "KAUÃ DE ALMEIDA PRADO",
        "DAPHNE POLLYANE DA SILVA RUFFATO",
        "PAMELA VITORIA RODRIGUES MACEDO",
        "JOÃO MIGUEL SILVA SANTO",
        "JOAO PEDRO GOMES DOS SANTOS"
    ],
    "7ºA": [
        "MAISA GOMES DE SANTANA",
        "WILLIAN MATEUS WILKER SANTOS MEDEIROS",
        "AGATA VITORIA ALMEIDA CAMPOS",
        "ALICE MAURINY DA SILVA DE SOUZA",
        "ANA VITORIA PRADO CORREIA",
        "ANA VITORIA SILVA FONTES",
        "ANDRA THAUANNY SOUZA SANTOS",
        "ANNA VICTORIA DE ALMEIDA",
        "BEATRIZ FERNANDES DE SOUZA",
        "CARLOS ALBERTO SINAGA RODRIGUES",
        "KAUA BERNARDES NASCIMENTO RIBEIRO",
        "DAYVID LUCAS SANTANA PIMENTA",
        "DOUGLAS MARCIEL OLIVEIRA DE ARRUDA",
        "FELIPE LORENZO DE CAMPOS GONÇALVES",
        "GABRIELLA GEREMINIANO ESTRAL DA SILVA",
        "GEOVANE HENRIQUE SANTOS LOUZADA",
        "HAYCHA ISABELLY PRADO PEDAIS",
        "KAIO EVERALDO DA SILVA LEMES",
        "KAUANNY RAFAELA OLIVEIRA DAS NEVES",
        "LUIZ MATHEWS GOMES DOS SANTOS",
        "MARCOS JOSÉ MENINO MENDES DE SOUZA",
        "MARIA LUIZA LEITE DE MIRANDA",
        "MARLOM SILVA REIS",
        "MATHEUS VINICIO SILVA DOS SANTOS",
        "MIRELLA BEATRIZ FERNANDES DE MEIRELES",
        "PEDRO MIGUEL SILVA DE ALMEIDA",
        "SAMUEL ALVES DA SILVA",
        "SAMUEL ALVES RIBEIRO DE SENA",
        "VANESSA MARIM RODRIGUES DA SILVA",
        "MARIA EDUARDA RODRIGUES SILVA",
        "ENZO GABRIEL MARTINS DE FARIAS",
        "GABRIEL PEREIRA BARBOSA"
    ],
    "7ºB": [
        "YANN GUILHERME GALVAO ALEXANDRIA",
        "YASMIM VITORIA MORAES DE ALMEIDA",
        "ALLANA VITORIA COSTA SILVA",
        "ANNE GABRIELLY BISPO DE PAULA",
        "CARLOS EDUARDO CARDOSO DA COSTA",
        "ENZO RODRIGUES HONORATO",
        "ESTHEFANE VITORIA SOARES CAETANO",
        "EVELLYN RAYANE DA SILVA SANTANA",
        "GIOVANNA ISADORA VITAL BRANDAO DE SOUZA",
        "HELIO MARCIO SANTOS ARAUJO",
        "ISAQUE OLIMPIO DA CRUZ",
        "JOÃO VICTOR DA COSTA MARQUES",
        "KASSIANY DO NASCIMENTO LIMA OLIVEIRA",
        "KETYLLEN MARIANNE PEREIRA DE ARAUJO",
        "LUCAS GABRIEL DA SILVA PAES",
        "LUCAS GABRIEL FAGUNDES PROFESSOR",
        "MAYRA ALMEIDA ORTOLAN",
        "MAYRA SOUZA PEREIRA DE ARRUDA",
        "NAWNHAM VITOR DA SILVA LEÃO",
        "NICOLLY VITORIA DOS ANJOS NASCIMENTO",
        "NOAH TAVARES DA SILVA",
        "SOPHIA ELOAH OLIVEIRA SILVA",
        "WALLYSON YAGO DA SILVA ALMEIDA",
        "JESSICA NICOLLY LIMA DA SILVA",
        "JOAO GABRIEL BRILHANTE",
        "KALIANY CRISTINA SANTOS DE ARRUDA",
        "LUKAS GABRIEL COSTA SAMPAIO",
        "SOPHIA GABRIELY COSTA SAMPAIO",
        "ALICE OLIVEIRA LEQUE",
        "MAYARA TAINA DA SILVA SANTOS NICANOR",
        "VALKSSANDRO SANTIAGO DE ARAUJO",
        "NICOLLY LAVINIA SANTANA PRADO",
        "MARY GIULIANA CARDOSO OLIVEIRA",
        "NUELLY SOPHYA DIAS DE LACERDA",
        "FELIPE LORENZO DE CAMPOS GONÇALVES"
    ],
    "7ºC": [
        "ANDREY WILLIAM OLIVEIRA DO NASCIMENTO",
        "ANTÔNIO MIGUEL ALMEIDA DE ARRUDA",
        "CAROLINE EDUARDA BISPO DOS SANTOS",
        "DIMILLY YASMIN LEITE DE SOUZA",
        "EMANUELLE DELGUINGARO SANTOS",
        "EVELLYN LARA CORREA DE ALMEIDA",
        "FERNANDA DE MOURA PORTILHO",
        "FERNANDA RAYSSA RODRIGUES DA SILVA",
        "MIKAELLY VITORIA FERREIRA CARVALHO",
        "NICOLAS GUILHERME DE ALMEIDA GOMES",
        "HELOYSA FERNANDA DOS SANTOS SOUZA",
        "ISABELLA VALENTINA DE OLIVEIRA MIRANDA",
        "JHONATA CABRAL DE OLIVEIRA",
        "JOÃO PEDRO SALVATERRA NOBRES",
        "LUAN GABRIEL MARTINS SILVA",
        "LUCAS GABRIEL BARROS PEDRO",
        "LUIS GUSTAVO SILVEIRA FREITAS PEREIRA",
        "MELISSA MARTINS SOUZA RIBEIRO",
        "NICOLLY TAMINE DINAGLEY FALCÃO",
        "PEDRO EMANUEL MARTINS MAROTO SANTOS",
        "PEDRO HENRIQUE ALMEIDA DE ARRUDA",
        "RYAN MELQUESIEL SOARES ARAUJO GUSMÃO",
        "SARA CRISTINA SEABRA DA SILVA",
        "SARAH VITORIA SANABRIA DO NASCIMENTO",
        "SOPHIA FERNANDES DE LIMA",
        "THIAGO DAVI PEREIRA DE QUEIROZ",
        "VALERY ALEJANDRA ECHENAGUCIA LEYVA",
        "YAGO GABRIEL CAVALCANTI GONCALVES",
        "YURI DE SOUZA FERREIRA",
        "WANDERSON HENRIQUE DE SOUZA SAMPAIO",
        "ISRAEL LAVY DE BARROS VIANA",
        "VYCTÓRIA CHRYSTINE FERREIRA CHAVES PIRES",
        "MARIA ALICE SANTIAGO PACHECO DA COSTA"
    ],
    "7ºD": [
        "ALICE VITORIA DE SOUZA HONORIO",
        "DAVI LUCAS ILDEFONSO DOS SANTOS",
        "DEREK HEITHOR SILVA BRUNO",
        "ENZO GABRIEL JOSE DIAS BARBOSA",
        "FERNANDA DE ALENCAR LIMA",
        "FERNANDA MATIAS DE ANDRADE MELO",
        "JOÃO GABRIEL PEREIRA DE SOUZA",
        "JULIANDRA CORREA MARÇAL",
        "KESIA SIQUEIRA BARBARA",
        "KIMBERLY YARA SANTOS MELLO",
        "LAUANY PRECILA RIBEIRO",
        "LUCAS GABRIEL GAUTO DOS SANTOS",
        "MARIANA DE RAMOS CORRÊA",
        "MATHEUS HENRIQUE DE SIQUEIRA GONÇALVES",
        "NATALLY YASMIM PEREIRA DE CAMPOS",
        "PAOLA BEATRIZ FERREIRA BATISTA",
        "RAISSA VITORIA SANTOS SOUZA",
        "SOPHIA GABRIELLY MIRANDA GARCIA",
        "YASMIM FERNANDA ALVES FERNANDES",
        "MARIA VITORIA VALERIO RAMOS",
        "LUCAS NAIAN SOUZA CARVALHO",
        "VANCLEI DA SILVA AMARAL",
        "DEYVID MIGUEL MAZETTO DA SILVA",
        "THALISON LUCAS FREIRE MORAIS DE FIGUEIREDO",
        "BEATRIZ DE JESUS SANTANA PINTO",
        "SAMUEL PRADO MARQUES",
        "LUCAS GABRYEL DE ALENCAR DA SILVA",
        "PETTERSON MATHEUS BARCELLOS PROFESSOR",
        "WILLIAN MATEUS WILKER SANTOS MEDEIROS"
    ],
    "8ºA": [
        "JOAO PEDRO TEIXEIRA DO NASCIMENTO",
        "ANA CLARA LARA SILVA",
        "ANA JULIA SANTOS TRINDADE DE OLIVEIRA",
        "CARLOS EDUARDO FIGUEIREDO PASSOS FERREIRA",
        "DAVI OLIVEIRA VIEIRA",
        "EMANUELY DE SOUZA JIMENEZ",
        "ERICK FELIPE OLIVEIRA SILVA",
        "ESTHER CRISTINA SEGOVIA OLIVEIRA",
        "HENDRYW LUCCAS FARDIM DA LUZ",
        "JULIA DA SILVA SOARES",
        "JÚLIA VITÓRIA ARAÚJO DA CONCEIÇÃO",
        "KAUAN JUNIOR DA SILVA SANTOS",
        "KAYKE LIMA LOPES",
        "LETICIA VITORIA NASCIMENTO DA SILVA",
        "LIVYA REBEKA GONÇALVES FERREIRA",
        "LORENA CORREA SILVA",
        "LUIZ FELIPE SILVA IRMÃO",
        "MARCYA CECILIA SINAGA RODRIGUES",
        "PEDRO DA SILVA PEREIRA",
        "RHUAN LUCAS ALVES LIMA",
        "SOPHIA MARIA DE OLIVEIRA ARAUJO",
        "SUMAYA RIBEIRO DE LIMA",
        "THIAGO MARTINS DE MELO DOS SANTOS",
        "VICTOR HUGO GOMES DE ALMEIDA",
        "WENDER RIAN FRANÇA DA SILVA",
        "WILSON JOHN PEREIRA DE ALMEIDA",
        "MAURY JANNY AMORIM DA SILVA",
        "MARCELO JUNIOR DE SOUZA FERREIRA",
        "VITTOR LORENZZO ALCANTARA SANTOS",
        "MARIA EDUARDA GOMES DE ARRUDA",
        "MAYA LAVINIA DE SOUZA BARROS LIMA"
    ],
    "8ºB": [
        "ALICE GABRIELLY ANUNCIAÇÃO DE ARRUDA",
        "ANA EMANUELY ALVES DA SILVA",
        "BRENDA YASMIN SIQUEIRA HOFFMANN",
        "CAUA CAMPOS VIEIRA",
        "DAVI SHIGUETAKA CORREA KUMAGAWA",
        "FERNANDO GUILHERME LARA RONDON",
        "GABRIEL PEREIRA SILVA",
        "HEBIO HENRIQUE FIGUEIREDO DO CARMO",
        "KELVIN CAETANO DOS SANTOS",
        "LAYS RAFAELLY DA SILVA ARAUJO",
        "LUANA MEL VALENTINA ANTENOR DE SOUSA",
        "MAIANNY CRISTINNY ALVES DE OLIVEIRA",
        "MARIA EDUARDA FERREIRA DA SILVA",
        "MARIA ROSA LEITE PEREIRA",
        "MAYARA RENATA RODRIGUES BATISTA DE AMORIM",
        "MIGUEL GIDEÃO MARTINS PEDROSA",
        "MIGUEL HENRIQUE DE AJALA NUNES",
        "PATRICK CESAR OLIVEIRA DE MORAES",
        "PEDRO ANTONIO COELHO DA SILVA",
        "PYETRO KAUA FERREIRA DA SILVA",
        "STEPHANY KAUANY NASCIMENTO MACHADO",
        "THALYSON EDUARDO GOMES DA SILVA",
        "THAYLLA HERMANUELLY GOMES MARQUES NASCIMENTO",
        "THIFANY NICOLI PRADO CARDOSO",
        "WENDER RAMOS DE OLIVEIRA FILHO",
        "YORAN ANTONIO CAMARGO DOS SANTOS",
        "YTURIEL ENRIQUE DA SILVA AMORIM",
        "ITALLO BRITO DA SILVA",
        "JHONNY LUCAS DE ALMEIDA E SILVA",
        "YANNE CAROLINY MARTINS DE ALMEIDA",
        "MATEUS PEREIRA DANTAS"
    ],
    "8ºC": [
        "ALICE MARIELE NECO DA SILVA",
        "ANA FLAVIA CORREA DE MORAES",
        "ANALICE FRANCO SANTOS",
        "ANNA JULIA RODRIGUES GOMES",
        "DAVID GOMES DA SILVA",
        "EDUARDA CARLOS DE ARRUDA",
        "ELLOÁ MARTINS LIMA OLIVEIRA",
        "FELIPH SILVA VAZ",
        "FLAVIO AUGUSTO VILA PROFESSOR",
        "GABRIELA PEREIRA BARBOSA",
        "GEOVANA ROCHA MARTINS",
        "HENZO DANIEL LIMA DA SILVA",
        "HIGOR ALEXANDRE MATOS DE ARRUDA",
        "ISABELLY PEREIRA MONTEIRO",
        "KAUÃ LUCAS FARDIM DE SOUZA",
        "KAUANY CLARA COSTA RODRIGUES",
        "LAUANY FIGUEIREDO SILVA",
        "MARCOS CRISTIANO SANTOS DA SILVA",
        "MARIA EDUARDA DOS SANTOS SILVA",
        "QUEILA WILLYANE DA SILVA SANTOS DE MELO",
        "RIHANNA CONCEIÇÃO QUEIROZ",
        "SARA BEATRIZ FERREIRA DA SILVA",
        "SOFYA AMORIM TOLEDO",
        "SUELLEN GEOVANA DA SILVA SATO",
        "VERONICA ALVES DE SOUZA",
        "YAN NICOLLAS DE ALMEIDA EREDIA",
        "ZURISMAR DE JESUS BOLIVAR GONZALEZ",
        "KAUANY DO NASCIMENTO LIMA OLIVEIRA",
        "LORENZO OLIVEIRA DE SOUZA SILVA",
        "SANTIAGO BEZERRA REZENDE",
        "ANNY CAROLINE ROCHA DA SILVA PEDROSO",
        "KERRISON SILVA DO NASCIMENTO",
        "YANNA THAIS SANTIAGO DOS SANTOS"
    ],
    "8ºD": [
        "ALLAN FELIPHE CARDOSO",
        "ANDRIELA PEREIRA BARBOSA",
        "ANTONNY OLIVEIRA DE SANTANA",
        "BIANCA VITORIA AMORIM DA COSTA",
        "CRISTYAN GABRIEL LEMES DE SOUZA",
        "DAFNY MARIA COLARES DE CARVALHO",
        "EMANUELLY CRISTINE LEITE DE MIRANDA",
        "FABIO MIGUEL DE OLIVEIRA RAMOS SILVA",
        "GABRIELY CRISTINA SILVA GONÇALVES JESUS",
        "HELENA FERNANDA DO ESPÍRITO SANTO AMARAL",
        "ISAQUE RODRIGUES DE JESUS BONFIM",
        "JAMILY ANDRADE ISAQUE",
        "JOÃO EMANUEL MARQUES NEVES",
        "JULIA GABRIELLY SIQUEIRA FRANÇA",
        "KAMILLY VITÓRIA FARIA",
        "KAUA RICHARD ARRUDA MELO",
        "KAUANE VITORIA GOMES DE ARRUDA",
        "LUAN GABRIEL QUEIROZ ALVES",
        "LUAN HENRIQUE SANTOS LOUZADA",
        "MARIA FERNANDA OLIVEIRA ROCHA DO PRADO",
        "MARIA RITHA DE ARRUDA E SILVA",
        "PEDRO ARTHUR LEMES DE SOUZA",
        "ROBERTHA VITORIA MARTINS ALVES",
        "RYHANA DOS SANTOS SOUZA",
        "ALICE VITORIA BARROS MASSUD OLIVEIRA",
        "JOAO JOAQUIM SILVA ROCHA",
        "JULIANY FERNANDES DE SOUZA MOREIRA",
        "SOPHIA SENA SOARES DA SILVA SANTOS",
        "PEDRO LUCAS DA SILVA",
        "THIFANY THAEME SILVA DE SOUZA",
        "WESLEY JUNIOR DE JESUS SANTANA RAMOS",
        "DAVI LUCAS SILVA LOPES",
        "MARHIA JULIA CASTRO DE JESUS",
        "LUDMYLLA MIKAELLY RODRIGUES MELO"
    ],
    "9ºA": [
        "ANGEL GABRIEL MEDINA MARCANO",
        "ANA BEATRIZ FERREIRA LEITE",
        "BEATRIZ HELOISA SILVA CRUZ",
        "BRENA MACENA DA SILVA",
        "CAIA DA SILVA CRUZ",
        "CARLOS HENRIQUE SILVA DE ALMEIDA",
        "DEIVID KAIC NASCIMENTO COSTA GARCEZ PEREIRA",
        "GEOVANNA ALVES FERRAZ DE OLIVEIRA",
        "GRACYLMA THALLYTA OLIVEIRA FERNANDES",
        "ISABELLA QUEIROZ MONTEIRO",
        "JOÃO GUILHERME GOMES",
        "JULIA VITÓRIA RODRIGUES DA SILVA",
        "KAIO PRADO DA SILVA",
        "KAWANNY BEATRIZ DA SILVA SANTOS",
        "LUCAS GABRIEL DO NASCIMENTO SOUZA",
        "LUIS GUILHERME DA SILVA SALINAS",
        "LUIZ HENRIQUE PEREIRA SILVA",
        "MARLON EDUARDO GEORGE MORENO",
        "PIERRE DIAS FERREIRA GOMES",
        "REINALDO ENZO FERREIRA RIBEIRO",
        "SAMUEL AUGUSTO DOS SANTOS PEREIRA",
        "SAYRON ROGER ARRUDA DA SILVA",
        "STHEFANY RAFAELLY RAMOS DE JESUS",
        "THIAGO HENRIQUE NASCIMENTO DA SILVA",
        "YOHAINE VITORIA CAVALCANTI GONÇALVES",
        "EMANUELE VITORIA DIAS DA SILVA",
        "KWYSTOPHER KENDRWICKY SOUZA BUENO",
        "ANNA ROBERTA DOS SANTOS NASCIMENTO",
        "EMANUELLY GONÇALVES SANTANA",
        "ALYSSA ISABELLA GUIA DA LUZ",
        "ANA SOPHIA CORREA DOS SANTOS",
        "ANNA JULIA SOARES DE OLIVEIRA",
        "ARTHUR CESAR ARAUJO NUNES",
        "BARBARA DE JESUS DUARTE VENTURA",
        "BRUNNA EDUARDA FERREIRA COSTA",
        "EDILAINE MARTINS DE JESUS"
    ],
    "9ºB": [
        "ANGELO ANTONIO VIEIRA DOS SANTOS",
        "ANIELLY VICTÓRIA GIL FONSECA",
        "EICKSON VENTURA DA SILVA PINTO",
        "EMANOEL DA COSTA SILVA",
        "FELIPE SOUZA GOMES",
        "FRITZNELSON GASTON",
        "HENRIQUE GABRIEL SILVA OLIVEIRA",
        "HITALLO ARTHUR CARDOSO DA CRUZ",
        "IKARO GUILHERME DOS SANTOS BORGES DE MIRANDA",
        "ISABELA VIEGAS SANTANA DA SILVA",
        "KAUANE CRISTINI DA SILVA ROSA",
        "LOREN VALENTINA ALMEIDA SILVA",
        "LUIS FELIPE SANTANA DOS SANTOS",
        "LUIS GUILHERME DA SILVA OLIVEIRA",
        "MARIA EDUARDA JESUS DA SILVA",
        "MAYARA SILVA DE MELO",
        "MELISSA KAUANA NUNES DE OLIVEIRA",
        "MIGUEL OLIVEIRA ROCHA DO PRADO",
        "RYCHELL MIRANDA DA SILVA SOARES",
        "UDSON CESAR BEZERRA LIMA",
        "VINICIUS HENRIQUE SANTIAGO DE ARAUJO",
        "YURI VICTOR DA SILVA SOARES",
        "DAVI REIS MACEDO",
        "KAIO CRISTIAN DA SILVA ROSA",
        "EDUARDA GABRIELE ARRUDA DOS SANTOS",
        "LARYSSA SANTOS SILVA",
        "ABIDO FILHO COSTA DA SILVA",
        "JULYANA NOGUEIRA DE ALENCAR",
        "ALÉXIA ARRUDA LOPES",
        "GUILHERME CORREA KUMAGAWA",
        "MARIA CLARA SANTANA SOARES",
        "ÍTALO GUILHERME PAES DE ARRUDA",
        "MURILO JOAQUIM MORAIS DE OLIVEIRA"
    ],
    "9ºC": [
        "ALESSANDRA PEREIRA DE QUEIRÓZ",
        "ANA CLARA LIMA DA SILVA",
        "ANNA BEATRIZ SOUZA SILVA DE FIGUEIREDO",
        "GUSTAVO HENRIQUE SILVA DOS SANTOS",
        "GUSTTAVO HENRIQUE MALHEIROS BENITES GOMES",
        "ISTELA JOSIANE DOS REIS CORE",
        "JOSE ROBERTO NETO JURELO",
        "THIAGO MATHEUS SILVA VENTURA",
        "WALLAN KAIKY SOARES BONIOLI",
        "VITORIA ESTER DE SOUZA",
        "ELOIZA EMANOELI DO NASCIMENTO",
        "CARLOS EDUARDO SOUZA CORREIA",
        "EMILLY EDUARDA BEZERRA DA SILVA",
        "KAMILLY VITORIA DA SILVA DA LUZ",
        "RENNYR RANGEL ALMEIDA DE SOUZA",
        "KELVYN EDUARDO ANDRADE FRANCO",
        "ELIZANGELA BEATRIZ ALVES LOPES",
        "MURILO JOAQUIM MORAIS DE OLIVEIRA",
        "ISABELLY SHOFIA RODRIGUES DE SOUZA",
        "LEONARDO FERREIRA DA SILVA",
        "WESLEY SANTOS VAZ",
        "EVILLYN CAROLINY RODRIGUES HOFFMANN",
        "LUIZ RENATO GIROLOMETTO DE SOUZA",
        "TARSO FERNANDO DE LIMA DOS SANTOS",
        "WENDER GABRIEL EVANGELISTA DE AQUINO",
        "BEATRIZ HELOISA SILVA CRUZ",
        "ANGEL GABRIEL MEDINA MARCANO",
        "STHEFANY RAFAELLY RAMOS DE JESUS",
        "YOHAINE VITORIA CAVALCANTI GONÇALVES",
        "GABRIEL MARQUES DOS SANTOS",
        "SAMIRA ALVES RIBEIRO",
        "UDSON CESAR BEZERRA LIMA"
    ],
    "9ºD": [
        "ALEXSANDRO PEREIRA DA GAMA FILHO",
        "ALFREDO DARIO AUTUNNO LEON",
        "ANA JULIA MORAIS DE OLIVERIA",
        "ANA TEREZA KUNZE CONSTANTINO MIRANDA",
        "ANNA SOPHIA AMARAL DE MORAES",
        "ANNY KARINE DA SILVA SAMPAIO",
        "CARLOS EDUARDO MENEZES DA SILVA",
        "EDNILSON ALVES DE SOUZA",
        "EDUARDA VITORIA FERREIRA DIAS",
        "EMANUELLY VITORIA DE SOUZA SILVA",
        "ERICK RIQUELME MARCONDES MUNIZ",
        "GABRIEL MARQUES DOS SANTOS",
        "GABRIELLY FERNANDA DE BARROS VIANA",
        "GUSTAVO HENRIQUE DOS SANTOS DE JESUS",
        "JOSE ANTONIO SANTANA GONÇALVES",
        "KAMILLY VICTORIA AMORIM NASCIMENTO",
        "LARYSSA DA SILVA SANTANA",
        "NITHALLY RONAYARA COSTA ALMEIDA",
        "OTAVIO LUCAS CONCEICAO SIQUEIRA",
        "SAMUEL LIMA DA SILVA",
        "VICTOR EMANUEL DE OLIVEIRA",
        "VITOR GABRIEL SOUZA DE JESUS",
        "CAYLLA CRISTYNA SANTOS DE ABREUU",
        "HADASSA GABRIELLY PASSOS AMORIM",
        "THAYANE CRISTINA CRUZ SILVA",
        "VICTOR ANANIAS CAMPOS GUIMARÃES E SILVA",
        "YURI RODRIGO DAMACENO DOS SANTOS",
        "SAMIRA ALVES RIBEIRO",
        "LUAN MARCOS NEVES DE SOUZA",
        "GABRIELA PEDROSO RAMOS",
        "LUCAS GABRIEL ALENCASTRO OLIVEIRA",
        "LUIS MIGUEL OLIVEIRA PEREIRA",
        "MARIA LUISA DE AMORIM SOARES",
        "MARIANI ISABELE OLIVEIRA MUNIZ",
        "MAURELIS VALENTINA LEREICO NATERA",
        "MICKAELLY DOS ANJOS PEDROSO",
        "PEDRO MIGUEL PESSOA SILVA"
    ],
    "PRA A": [
        "ALISON SOARES RAMOS",
        "ANDRÉ RAMOS",
        "HENNING BRAND SANTOS DELGADO",
        "JASMIM CRISTINA DE OLIVEIRA LOUREIRO MARTINS",
        "JOYCE LAUANY BEZERRA LIMA",
        "KAUE ABREU MOURA",
        "LEONAN HENRICK SANTOS DE ALMEIDA",
        "LUDMILA RAYANE MARTINS DE LIMA",
        "VINICIUS PEREIRA DE SOUZA",
        "VINICIUS SILVA VASQUES",
        "WALIFY IAN DE PAULA RODRIGUES",
        "YKARO DIMAS RAMOS DIAS",
        "GUILHERME HENRIQUE SIMOES DA SILVA",
        "GENIVALDO SILVA SANTOS",
        "JULIA EMANUELLY XAVIER SANTOS",
        "RICHARLISON CABRAL DE SOUZA",
        "PEDRO HENRIQUE TEIXEIRA DA SILVA",
        "RHAMILE LUARA CORREA DE SOUZA",
        "ALVARO RICHARD NASCIMENTO NOBRE",
        "ANA VITORIA DO NASCIMENTO MIRANDA",
        "SARAH MACHADO DE ALMEIDA",
        "DAVID CHAVES DUROURE",
        "MARCELO NEVES DE SOUZA FILHO",
        "ANA BEATRIZ FERREIRA SILVA DE ALMEIDA",
        "KATIELLY IASMIM MARTINS DE OLIVEIRA",
        "ESTEFANY TAINA MORAIS DE CARVALHO",
        "BRAYAN ALEXANDRE GOMES MIESE",
        "ANDRES JOEL VERA QUINTERO",
        "SOLMARY GABRIELA ARRIOJAS RODRIGUEZ",
        "BRENNO HENRIQUE MENESES MAGALHAES",
        "YULEIDYS ALEJANDRA MEDINA CURAPA"
    ]
};

let bancoDeAlunos = {};
let historico = [];

window.onload = function() {
    const cacheAlunos = localStorage.getItem('db_turmas_v12');
    if (cacheAlunos) {
        bancoDeAlunos = JSON.parse(cacheAlunos);
        Object.keys(alunosIniciais).forEach(turma => {
            if (!bancoDeAlunos[turma]) bancoDeAlunos[turma] = [];
            alunosIniciais[turma].forEach(nome => {
                if(!bancoDeAlunos[turma].includes(nome)) bancoDeAlunos[turma].push(nome);
            });
        });
    } else {
        bancoDeAlunos = Object.assign({}, alunosIniciais);
    }
    
    const cacheHistorico = localStorage.getItem('db_hist_v12');
    historico = cacheHistorico ? JSON.parse(cacheHistorico) : [];

    renderizarLista();
    document.getElementById('dataOcorrencia').valueAsDate = new Date();
    
    document.addEventListener('click', function(e) {
        if (!e.target.closest('#alunoNome') && !e.target.closest('#listaSugestoes')) {
            document.getElementById('listaSugestoes').style.display = 'none';
        }
    });
};

function filtrarNomesGlobais() {
    const input = document.getElementById('alunoNome');
    const listaDiv = document.getElementById('listaSugestoes');
    const termo = input.value.toUpperCase().trim();
    
    listaDiv.innerHTML = '';
    
    if (termo.length === 0) {
        listaDiv.style.display = 'none';
        document.getElementById('selectSerie').value = "";
        document.getElementById('selectTurmaLetra').value = "";
        return;
    }

    let filtrados = [];
    for (let turma in bancoDeAlunos) {
        bancoDeAlunos[turma].forEach(nome => {
            if (nome.includes(termo)) {
                filtrados.push({nome: nome, turma: turma});
            }
        });
    }
    
    if (filtrados.length > 0) {
        listaDiv.style.display = 'block';
        const maxResultados = filtrados.slice(0, 15);

        maxResultados.forEach(item => {
            const div = document.createElement('div');
            div.className = 'item-sugestao';
            
            const regex = new RegExp(`(${termo})`, 'gi');
            const nomeDestacado = item.nome.replace(regex, "<span style='color:var(--e63946); background:transparent; padding:0;'>$1</span>");

            div.innerHTML = `<div><strong>${nomeDestacado}</strong></div> <span class="item-turma">Turma: ${item.turma}</span>`;
            
            div.addEventListener('mousedown', function(e) { e.preventDefault(); selecionarAluno(item.nome, item.turma); });
            div.addEventListener('touchstart', function(e) { e.preventDefault(); selecionarAluno(item.nome, item.turma); });
            
            listaDiv.appendChild(div);
        });
    } else {
        listaDiv.style.display = 'block';
        const addDiv = document.createElement('div');
        addDiv.className = 'item-sugestao item-add';
        addDiv.innerHTML = `⚠️ Não achei na lista.<br><br>Preencha os campos "Série" e "Turma" abaixo e toque AQUI para cadastrar o(a) <b>"${termo}"</b> para as próximas vezes!`;
        addDiv.addEventListener('mousedown', function(e) { e.preventDefault(); registrarNovoAlunoForcado(termo); });
        addDiv.addEventListener('touchstart', function(e) { e.preventDefault(); registrarNovoAlunoForcado(termo); });
        listaDiv.appendChild(addDiv);
    }
}

function selecionarAluno(nome, turma) {
    document.getElementById('alunoNome').value = nome;
    document.getElementById('listaSugestoes').style.display = 'none';
    
    let matchSerie = "";
    let matchLetra = "";

    if (turma.startsWith("PRA")) {
        matchSerie = "PRA ";
        matchLetra = turma.replace("PRA", "").trim();
    } else {
        matchSerie = turma.substring(0, 2); 
        matchLetra = turma.substring(2).trim(); 
    }

    document.getElementById('selectSerie').value = matchSerie;
    document.getElementById('selectTurmaLetra').value = matchLetra;
}

function registrarNovoAlunoForcado(nome) {
    const serie = document.getElementById('selectSerie').value;
    const letra = document.getElementById('selectTurmaLetra').value;
    
    if (!serie || !letra) { 
        alert("Atenção: Selecione primeiro a Série e a Turma nas caixinhas abaixo antes de tentar adicionar!"); 
        return; 
    }

    const turmaFormatada = serie === "PRA " ? `PRA ${letra}` : `${serie}${letra}`;

    if (!bancoDeAlunos[turmaFormatada]) bancoDeAlunos[turmaFormatada] = [];
    bancoDeAlunos[turmaFormatada].push(nome);
    localStorage.setItem('db_turmas_v12', JSON.stringify(bancoDeAlunos));
    
    selecionarAluno(nome, turmaFormatada);
    alert(`O aluno ${nome} foi cadastrado e aparecerá nas suas próximas buscas!`);
}

function verificarOutro() {
    const val = document.getElementById('selectOcorrencia').value;
    const manualInput = document.getElementById('ocorrenciaManual');
    manualInput.style.display = (val === 'OUTRO') ? 'block' : 'none';
}

function adicionarOcorrencia() {
    const nome = document.getElementById('alunoNome').value.toUpperCase().trim();
    const serie = document.getElementById('selectSerie').value;
    const letra = document.getElementById('selectTurmaLetra').value;
    const dataRaw = document.getElementById('dataOcorrencia').value;
    const responsavel = document.getElementById('selectResponsavel').value;
    
    let desc = document.getElementById('selectOcorrencia').value;
    if (desc === 'OUTRO') desc = document.getElementById('ocorrenciaManual').value.trim();

    if (!nome) { alert("Digite ou pesquise o nome do aluno!"); return; }
    if (!serie || !letra) { alert("A Série e Turma devem estar preenchidas!"); return; }
    if (!dataRaw) { alert("Selecione a Data."); return; }
    if (!responsavel) { alert("Selecione o Responsável pela notificação!"); return; }
    if (!desc) { alert("Selecione ou digite o motivo da ocorrência."); return; }

    const turma = serie === "PRA " ? `PRA ${letra}` : `${serie}${letra}`;
    
    if (!bancoDeAlunos[turma]) bancoDeAlunos[turma] = [];
    if (!bancoDeAlunos[turma].includes(nome)) bancoDeAlunos[turma].push(nome);
    
    const registro = { 
        id: Date.now(), 
        data: dataRaw, 
        nome: nome, 
        turma: turma, 
        responsavel: responsavel,
        desc: desc 
    };

    historico.unshift(registro); 
    localStorage.setItem('db_turmas_v12', JSON.stringify(bancoDeAlunos));
    localStorage.setItem('db_hist_v12', JSON.stringify(historico));
    
    renderizarLista();
    
    document.getElementById('alunoNome').value = "";
    document.getElementById('selectSerie').value = "";
    document.getElementById('selectTurmaLetra').value = "";
    document.getElementById('selectResponsavel').value = "";
    document.getElementById('selectOcorrencia').value = "";
    document.getElementById('ocorrenciaManual').value = "";
    document.getElementById('ocorrenciaManual').style.display = "none";
    document.getElementById('listaSugestoes').style.display = 'none';
    
    alert("Ocorrência Registada com Sucesso! ✅");
}

function deletar(id) {
    if(confirm("Deseja apagar este registo?")) {
        historico = historico.filter(item => item.id !== id);
        localStorage.setItem('db_hist_v12', JSON.stringify(historico));
        renderizarLista();
    }
}

function renderizarLista() {
    const container = document.getElementById('listaOcorrencias');
    container.innerHTML = "";
    if(historico.length === 0) {
        container.innerHTML = "<p style='text-align:center; color:#999; margin-top:20px;'>Nenhum registo no histórico.</p>";
        return;
    }
    historico.forEach(item => {
        const dataParts = item.data.split('-');
        const dataFmt = `${dataParts[2]}/${dataParts[1]}/${dataParts[0]}`;
        const responsavelLabel = item.responsavel ? item.responsavel : "Não informado";

        const card = document.createElement('div');
        card.className = 'card-ocorrencia';
        card.innerHTML = `
            <div class="card-top">
                <span class="card-date">📅 ${dataFmt}</span>
                <span class="card-turma">${item.turma}</span>
            </div>
            <strong class="card-nome">${item.nome}</strong>
            <div class="card-responsavel">👤 ${responsavelLabel}</div>
            <div class="card-desc">${item.desc}</div>
            <div class="card-footer">
                <button class="btn-danger" onclick="deletar(${item.id})">🗑️ Excluir</button>
            </div>
        `;
        container.appendChild(card);
    });
}

function exportarExcel() {
    if(historico.length === 0) { alert("Não há registos."); return; }
    let html = "<table border='1'><tr><th>Data</th><th>Nome do Aluno</th><th>Turma</th><th>Responsável</th><th>Motivo</th></tr>";
    historico.forEach(h => {
        const resp = h.responsavel ? h.responsavel : "";
        html += `<tr><td>${h.data}</td><td>${h.nome}</td><td>${h.turma}</td><td>${resp}</td><td>${h.desc}</td></tr>`;
    });
    html += "</table>";
    const a = document.createElement('a');
    const dataAtual = new Date().toLocaleDateString().replace(/\//g, '-');
    a.href = 'data:application/vnd.ms-excel,' + encodeURIComponent(html);
    a.download = `Relatorio_Ocorrencias_${dataAtual}.xls`;
    a.click();
}

function fazerBackup() {
    const dados = JSON.stringify({ alunos: bancoDeAlunos, historico: historico });
    const blob = new Blob([dados], {type: "application/json"});
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `BACKUP_ESCOLA_${Date.now()}.json`;
    a.click();
}

function triggerRestore() {
    document.getElementById('inputRestore').click();
}

function restaurarBackup(e) {
    const reader = new FileReader();
    reader.onload = function(event) {
        try {
            const dados = JSON.parse(event.target.result);
            if(dados.alunos && dados.historico) {
                bancoDeAlunos = dados.alunos;
                historico = dados.historico;
                localStorage.setItem('db_turmas_v12', JSON.stringify(bancoDeAlunos));
                localStorage.setItem('db_hist_v12', JSON.stringify(historico));
                alert("Backup restaurado com sucesso!");
                location.reload();
            } else { alert("Arquivo inválido."); }
        } catch(err) { alert("Erro ao ler o arquivo."); }
    };
    reader.readAsText(e.target.files[0]);
}
